### ISSUE TITLE
[Bug] Can't use any `alloy_primitives::Uint` other than `U256` in contract boundaries

### ISSUE THREAD

**Issue by alexfertel** [OffchainLabs/stylus-sdk-rs#117]
Given the following contract:

```rust
sol_storage! {
    pub struct Test {
        uint8 t;
    }
}

#[external]
impl Test {
    pub fn getter(&mut self) -> U8 {
        self.t.get()
    }

    pub fn setter(&mut self, t: U8) {
        self.t.set(t)
    }
}
```

we get this compiler error:

```terminal
error[E0271]: type mismatch resolving `<IntBitCount<8> as SupportedInt>::Uint == Uint<8, 1>`
  --> src/lib.rs:43:1
   |
43 | #[external]
   | ^^^^^^^^^^^ expected `Uint<8, 1>`, found `u8`
   |
   = note: expected struct `alloy_primitives::Uint<8, 1>`
                found type `u8`
   = note: required for `alloy_primitives::Uint<8, 1>` to implement `AbiType`
   = note: required for `alloy_primitives::Uint<8, 1>` to implement `EncodableReturnType`
```
---

Given that `Storage*` types use `alloy_primitives` at the accessor boundaries I would expect the SDK to handle this conversion for contract boundaries for me. Note that `U256` works fine.

I get the same error inside the SDK if we add this [here](https://github.com/OffchainLabs/stylus-sdk-rs/blob/290326c9f28057f20cbe881738b913ed34c20755/stylus-sdk/src/abi/impls.rs#L59):

```rust
test_type!(uint8, "uint8", Uint<8, 1>);
```
---

A simple workaround for now is to use Rust types at the contract boundaries and make the conversion explicit. In the above example, that would be something like:

```rust
    pub fn getter(&mut self) -> u8 {
        self.t.get().byte(0)
    }
```

**Comment by chrisco512** [comment]
Thanks for bringing this up. This is on our radar and will be fixed in a future release.
