### ISSUE TITLE
How to Implement StorageType for thridtype 

### ISSUE THREAD

**Issue by DaviRain-Su** [OffchainLabs/stylus-sdk-rs#51]
I papre implement ibc protocol on arbitrum, but meet problem, does have any tutorials implment StorageType for Thtrid type, example Height, this is define, https://github.com/cosmos/ibc-rs/blob/dc8e4161dd5e00a2031cf3feb58dad1ed7e26bdb/crates/ibc/src/core/ics02_client/height.rs#L32

**Comment by rachel-bousfield** [comment]
Hi! In this example, it may be better to just declare a struct like
```rs
#[solidity_storage]
pub struct Height {
    /// Previously known as "epoch"
    revision_number: u64,
    /// The height of a block
    revision_height: u64,   
}
```

Or, at your preference
```sol
sol_storage! {
    pub struct Height {
        uint64 revision_number;
        uint64 revision_height;
    }
}
```

**Comment by rachel-bousfield** [comment]
I'm not entirely sure I follow the question. Are you asking about implementing the trait for 3rd party types?
