### ISSUE TITLE
Project template not compatible with workspaces

### ISSUE THREAD

**Issue by target-san** [OffchainLabs/stylus-sdk-rs#55]
The current template used to in `cargo stylus new` contains `[profile]` section in `Cargo.toml` which makes it incompatible with workspaces. Since that template has `.cargo/config.toml` anyway, it would be reasonable to move all profile settings there

**Comment by joshuacolvin0** [comment]
This PR moved `[profile]` to `.cargo`: 
https://github.com/OffchainLabs/stylus-hello-world/pull/15/files
